### ISSUE TITLE
NEXT_PUBLIC_ Prefix 

### ISSUE THREAD

**Issue by ffdfo** [ColeBlender/supabase-auth-tutorial#1]
all info are stored in cookies you don't need to remove NEXT_PUBLIC_ 

![image](https://github.com/ColeBlender/supabase-auth-tutorial/assets/55764745/8b509e9c-ec11-4a64-bf4d-c96661fc1cc6)

**Comment by ColeBlender** [comment]
Yes, the access token is stored in cookies but you cannot deduce the supabase_url and supabase_anon_key from this information alone which means they are secure. If you don't remove NEXT_PUBLIC then they will be directly visible from the client which then allows anyone to use them thus compromising the security of your app
